version: "1.0"
info:
  model: int-scaffold
packages:
- name: Json_xmlProject
  gitServerName: shabee_12
  gitUrl: https://github.com/AnsRizvi-umerco
  gitUsername: ShabeeHaider-umerco
  gitBranch: main
